email: dev@monero.cc
name: Monero
description: Private. Secure. Untraceable.
keywords: "monero, xmr, bitmonero, cryptocurrency"
baseurl: ""
url: "https://getmonero.org"

markdown: kramdown

exclude: ["README.md"]

paginate: 10
paginate_path: blog/page:num/