- platform: Windows, 64-bit
  icon: windows.svg
  url: win64
  hash: facbeb2e408cf8b9a46534363eba161dbb047654
  version: 0.8.8.6
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  url: win32
  hash: none
  version: 0.8.8.6
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  url: mac64
  hash: 7069de92083fb7831b063cc152e8f35508ff61bf
  version: 0.8.8.6
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  url: linux64
  hash: 29bc436c51cc2c9d571a0bfbf12fddab2e75a10b
  version: 0.8.8.6
  blockchain: linux

- platform: FreeBSD, 64-bit
  icon: freebsd.svg
  url: freebsd64
  hash: 9fd0005b697e146a26a0bf9e3cd0c89b978f7fbd
  version: 0.8.8.6
  blockchain: freebsd

- platform: Raspberry Pi / ARM
  icon: arm.svg
  url: arm
  hash: none
  version: 0.8.8.6
  blockchain: arm

- platform: Source Code
  icon: github.svg
  url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)