- platform: Windows, 64-bit
  icon: windows.svg
  url: win64
  hash: 9d939613c0eba872a3dacd7fda572f4c7d2279207ce1ec0b15b46da4e1ccd5b9
  version: 0.9.4.0
  tag: Hydrogen Helix
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  url: win32
  hash: c9e4abc19c767ab570c2d0a9d504ba75d73eea26e7cf719a1260fdbb9469c250
  version: 0.9.4.0
  tag: Hydrogen Helix
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  url: mac64
  hash: ded52162d34d5a726b53ffd14ebbf02388d9b396f3f4e278a4755e5286b1aeab
  version: 0.9.4.0
  tag: Hydrogen Helix
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  url: linux64
  hash: 0b3610c9b301ea14174ce700923a604909fa7cbd9335849112c9d6cfb07a1a43
  version: 0.9.4.0
  tag: Hydrogen Helix
  blockchain: linux

- platform: Linux, 32-bit
  icon: linux.svg
  url: linux32
  hash: c070125bb885c5b887d3adce866e9bb941ed790485ef34444e62e0881fe8852a
  version: 0.9.4.0
  tag: Hydrogen Helix
  blockchain: linux

- platform: ARMv7
  icon: arm.svg
  url: arm
  hash: c312ba0810bf04ab2e28b61a50de2a83c1c614fd789bab4cacacb716134a7239
  version: 0.9.3.0
  tag: Hydrogen Helix
  blockchain: arm

- platform: Source Code
  icon: github.svg
  url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)