- platform: Windows, 64-bit
  id: windows
  icon: icon-windows
  cli_url: win64
  cli_hash: afafa1067ed0b000685084dff1e7ab044425fc323ae8761558b02c9a36a9011c
  gui_url: win64
  gui_hash: e4f3c7203b383845945a25e4f00e49ce80982b8fe34131bb39d42f04f0b671f4
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: win

- platform: Windows, 32-bit
  icon: icon-windows
  cli_url: win32
  cli_hash: 5f0286b50e3dd19272329ab5150de2d652d1f460d3842836c21dab8c7010344b
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: win

- platform: Mac OS X, 64-bit
  id: mac
  icon: icon-apple
  cli_url: mac64
  cli_hash: 12617e006237e271e27ecbc34047c3804b68c48e87e5ffe524abcac466579b05
  gui_url: mac64
  gui_hash: f6e14fb4956d95dd8f49056259188cf43d37eb9dbd1e3a5a38b5d14ee8291be5
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: mac

- platform: Linux, 64-bit
  id: linux
  icon: icon-linux
  cli_url: linux64
  cli_hash: fa7742c822f3c966aa842bf20a9920803d690d9db02033d9b397cefc7cc07ff4
  gui_url: linux64
  gui_hash: 3446f1b6487decdfe8e57a863fbfe3f2bedf043e421812674067c40928340eaa
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: linux

- platform: Linux, 32-bit
  icon: icon-linux
  cli_url: linux32
  cli_hash: d1e503e0e5c327a7c3ba8a55a2c227f04acdca47b8396c2cd35c583919056dec
  gui_url: linux32
  gui_hash: 9eea3fcd87357f9ef8b7a59a23ead208d7d3d9adfcba02ed73079f8fb1e5ad83
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: linux

- platform: ARMv7
  id: arm
  icon: icon-arm
  cli_url: linuxarm7
  cli_hash: 491e42a29f09b927c9b1311c4682ced7bc7cbb51e2a6469b74ae42ef647d59ab
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: arm

- platform: ARMv8
  icon: icon-arm
  cli_url: linuxarm8
  cli_hash: 61b4b2aa79a0653f0809c29c5846517e40033dba78779155a26a4a4cf7e0c4d8
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: arm

- platform: FreeBSD, 64-bit
  id: bsd
  icon: icon-freebsd
  cli_url: freebsd64
  cli_hash: 9cabc1f22674d787009a339796994ac67d1f2c00c13e5d1fbb6f63f7df9d57b0
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: freebsd

- platform: DragonflyBSD, 64-bit
  id: bsd
  icon: icon-dragonflybsd
  cli_url: dragonflybsd64
  cli_hash: c25c0f603ca5c96cb5963aaa2905edff390b7a97f654106911ffad8639deee7c
  version: 0.11.0.0
  tag: Helium Hydra
  blockchain: freebsd

- platform: Source Code & Blockchain
  id: source
  icon: icon-github
  cli_url: https://github.com/monero-project/bitmonero
  cli_hash: source
  version: Bleeding edge (possibly unstable)
  
- platform: Mobile & Light Wallets
  id: mobilelight
  
- platform: Hardware Wallets
  id: hardware
