- platform: Windows, 64-bit
  icon: windows.svg
  url: win64
  hash: 246115b0da133e0203dc78d26bbc82e9b76a178939bff8d4541bf04a02a19854
  version: 0.9.3.0
  tag: Hydrogen Helix
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  url: win32
  hash: 4663222a810ad854da1fc9d665e51252e61ddb1a8f69de3a31ad195386d445a2
  version: 0.9.3.0
  tag: Hydrogen Helix
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  url: mac64
  hash: f471a420485413d5fcb1b19065a3b4e9a68c49596ddd6291787ad34121bad32c
  version: 0.9.3.0
  tag: Hydrogen Helix
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  url: linux64
  hash: 9e6747b69642389e98ca5f70cec7276f7af7156e5dce95409a8da7cccff5876e
  version: 0.9.3.0
  tag: Hydrogen Helix
  blockchain: linux

- platform: Linux, 32-bit
  icon: linux.svg
  url: linux32
  hash: 90c51c4a68f78ac2262a7b5a676f02d43ba7b9b6800b8b150d89980604c969f2
  version: 0.9.3.0
  tag: Hydrogen Helix
  blockchain: linux

- platform: ARMv7
  icon: arm.svg
  url: arm
  hash: c312ba0810bf04ab2e28b61a50de2a83c1c614fd789bab4cacacb716134a7239
  version: 0.9.3.0
  tag: Hydrogen Helix
  blockchain: arm

- platform: Source Code
  icon: github.svg
  url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)