- platform: Windows, 64-bit
  icon: windows.svg
  url: win64
  hash: 303840d7fb997b2f1efc280fd19ba84003ecff85
  version: 0.9.1.0
  tag: Hydrogen Helix
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  url: win32
  hash: none
  version: 0.9.1.0
  tag: Hydrogen Helix
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  url: mac64
  hash: d6c776878fd3d47f149fc9be4e76cf2d03d5a725
  version: 0.9.1.0
  tag: Hydrogen Helix
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  url: linux64
  hash: 4149de91c10b56ff091070acca80d233fbd5a797
  version: 0.9.1.0
  tag: Hydrogen Helix
  blockchain: linux

- platform: FreeBSD, 64-bit
  icon: freebsd.svg
  url: freebsd64
  hash: 9fd0005b697e146a26a0bf9e3cd0c89b978f7fbd
  version: 0.8.8.6
  tag: Release
  blockchain: freebsd

- platform: Raspberry Pi / ARM
  icon: arm.svg
  url: arm
  hash: none
  version: 0.9.1.0
  tag: Hydrogen Helix
  blockchain: arm

- platform: Source Code
  icon: github.svg
  url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)