- platform: Windows, 64-bit
  icon: windows.svg
  url: /downloads/win64
  hash: facbeb2e408cf8b9a46534363eba161dbb047654
  version: 0.8.8.6
- platform: Mac OS X, 64-bit
  icon: apple.svg
  url: /downloads/mac64
  hash: 7069de92083fb7831b063cc152e8f35508ff61bf
  version: 0.8.8.6
- platform: Linux, 64-bit
  icon: linux.svg
  url: /downloads/linux64
  hash: 16f3f55bcfbfae6135cbeda6574f651890a8be64
  version: 0.8.8.6
- platform: Mac OS X, 64-bit
  icon: freebsd.svg
  url: /downloads/freebsd64
  hash: 9fd0005b697e146a26a0bf9e3cd0c89b978f7fbd
  version: 0.8.8.6
