- platform: Windows, 64-bit
  icon: windows.svg
  cli_url: win64
  hash: e852642c42bc9ed6a248fea0e0bb8e9e2563cdf9a4dfdd40b96226a3cadd874e
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  cli_url: win32
  hash: 8ac825d89f58a07be65f4f96ddd1e22ef4fb9156d28d12381ade6e3a070b18cb
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  cli_url: mac64
  hash: 685a0262b9add448a516baac3dc81d2dda559fdba000afcf6480e9b2dddf107b
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  cli_url: linux64
  hash: bf27eb173a775b62716b5fd1d1921f81c8d3b91187b190a22f2a6d82811915fd
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: linux

- platform: Linux, 32-bit
  icon: linux.svg
  cli_url: linux32
  hash: 5ce1475090dfc7897824de62b44771af6de395631540dee6361f0c32a82885ac
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: linux

- platform: ARMv7
  icon: arm.svg
  cli_url: arm7
  hash: 173c4f481587799b0ca8947826778eae75611ef4d6bce765df5915ffa12f91b8
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: arm

- platform: ARMv8
  icon: arm.svg
  cli_url: arm8
  hash: 26ad255a94d76acdce4e649d19d709181918a47df10ea9d00f9c14acf7b0129f
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: arm

- platform: FreeBSD, 64-bit
  icon: freebsd.svg
  cli_url: freebsd64
  hash: fec177e65a07f845cbcf64b7e39de8decee9cb04bf3f603dd38cec3a363f4d90
  version: 0.10.2.0
  tag: Wolfram Warptangent
  blockchain: freebsd

- platform: Source Code
  icon: github.svg
  cli_url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)