- platform: Windows, 64-bit
  icon: windows.svg
  cli_url: win64
  hash: 2fbda6f6b1051053703e40cf77b6c6e11334509ad03a3c22d89b6bcb05615910
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  cli_url: win32
  hash: da628a45adfcb8be44df06ac904711d644d608c4eb6479a5d256062a5f6d74de
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  cli_url: mac64
  hash: fd17d55a8c9e901ff4064c39d9e14786cdd077aff9b3bb556e60d3a5e322050c
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  cli_url: linux64
  hash: 8db80f8cc4f80d4106db807432828df730a59eac78972ea81652aa6b9bac04ad
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: linux

- platform: Linux, 32-bit
  icon: linux.svg
  cli_url: linux32
  hash: abc99f3928f4083bd1a380a869253e07bee9950e0aeb6388e9493bc0f0ec3f53
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: linux

- platform: ARMv7
  icon: arm.svg
  cli_url: linuxarm7
  hash: 8473fa20e0db4a3d3e46120cdf92c55be6a159478c511e21f7b77aa05d6c1910
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: arm

- platform: ARMv8
  icon: arm.svg
  cli_url: linuxarm8
  hash: 451f65e4846b92d54859e22a5d92124557b397b4208d8752d5289d0262573c3c
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: arm

- platform: FreeBSD, 64-bit
  icon: freebsd.svg
  cli_url: freebsd64
  hash: 4c66a76752e18ae70b5fb1c728f0d2780eb129a6c8c7d0dee7ba02e05d91efae
  version: 0.10.3.1
  tag: Wolfram Warptangent
  blockchain: freebsd

- platform: Source Code
  icon: github.svg
  cli_url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)