- platform: Windows, 64-bit
  icon: windows.svg
  url: win64
  hash: 33453727a8a49e07605dfee4b16aeb78816238a0e5c07dbaf19840f56f8d2cd4
  version: 0.10.0.0
  tag: Wolfram Warptangent
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  url: win32
  hash: b0b7898050e6de2bc2aa443fa783cf275683513c0d3714e66fe00e2c75378af6
  version: 0.10.0.0
  tag: Wolfram Warptangent
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  url: mac64
  hash: 204babf52d76e513d1f16527be4b3fb30d3ffbdd7528bf3997e4c1b5b301c9a8
  version: 0.10.0.0
  tag: Wolfram Warptangent
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  url: linux64
  hash: 6fe4cdb98d6ea7d2eded79841f70cb64edb840fcb2c84b904a1114424cffc5b1
  version: 0.10.0.0
  tag: Wolfram Warptangent
  blockchain: linux

- platform: Linux, 32-bit
  icon: linux.svg
  url: linux32
  hash: 89c9d2904c0de308eb31695af70084008c5880a2c0628de2fee8e47dd23967ea
  version: 0.10.0.0
  tag: Wolfram Warptangent
  blockchain: linux

- platform: ARMv7
  icon: arm.svg
  url: arm
  hash: cced4cad630e6b5e7131b9d079c3d176dfea79915b9080bdba199508c69e377b
  version: 0.10.0.0
  tag: Wolfram Warptangent
  blockchain: arm

- platform: Source Code
  icon: github.svg
  url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)