- platform: Windows, 64-bit
  icon: windows.svg
  url: win64
  hash: 727a53dd154b61fd653f81da27788077fdf519301c81d3c1eb033c1ff2bf97c6
  version: 0.10.1.0
  tag: Wolfram Warptangent
  blockchain: win

- platform: Windows, 32-bit
  icon: windows.svg
  url: win32
  hash: ce77137b33bcaeb59273cb73b86e426e35e6209fb52a7e74fd9432a5a3018041
  version: 0.10.1.0
  tag: Wolfram Warptangent
  blockchain: win

- platform: Mac OS X, 64-bit
  icon: apple.svg
  url: mac64
  hash: 447cebae257864b3706a8622f495bfd9fae780a6b277e1e31ac83bef7bc855c6
  version: 0.10.1.0
  tag: Wolfram Warptangent
  blockchain: mac

- platform: Linux, 64-bit
  icon: linux.svg
  url: linux64
  hash: bf09eea27c957e7e2bdd62dac250888b301d4d25abe18d4a5b930fa7477708c7
  version: 0.10.1.0
  tag: Wolfram Warptangent
  blockchain: linux

- platform: Linux, 32-bit
  icon: linux.svg
  url: linux32
  hash: 9a18d274970df85d6bc926dc99407959c680c36f19017996be9c758f6c02cf06
  version: 0.10.1.0
  tag: Wolfram Warptangent
  blockchain: linux

- platform: ARMv7
  icon: arm.svg
  url: arm
  hash: 57221605997a3cd815f2a9689486abbdb124263fff047ca61068900eb7cb1839
  version: 0.10.1.0
  tag: Wolfram Warptangent
  blockchain: arm

- platform: FreeBSD, 64-bit
  icon: freebsd.svg
  url: freebsd64
  hash: 3858d4786b65a37e981b142e9c0f256ac66662314794d05f595c4c30cb5b6ddb
  version: 0.10.1.0
  tag: Wolfram Warptangent
  blockchain: freebsd

- platform: Source Code
  icon: github.svg
  url: https://github.com/monero-project/bitmonero
  hash: source
  version: Bleeding edge (possibly unstable)